---
- name: Wait for Under Replicated Partitions Metric to return 200
  uri:
    url: "http://localhost:{{kafka_broker_jolokia_port}}/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5

- name: Wait for Under Replicated Partitions Metric to return Data
  uri:
    url: "http://localhost:{{kafka_broker_jolokia_port}}/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
    status_code: 200
  register: result
  until: result['json']['value'] is defined
  retries: 60
  delay: 5

# curl localhost:7771/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions
# {"request":{"mbean":"kafka.server:name=UnderReplicatedPartitions,type=ReplicaManager","type":"read"},"value":{"Value":0},"timestamp":1565819946,"status":200}
- name: Wait for Under Replicated Partitions Metric to equal Zero
  uri:
    url: "http://localhost:{{kafka_broker_jolokia_port}}/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
    return_content: yes
    status_code: 200
  register: result
  until: result['json']['value']['Value'] == 0
  retries: 60
  delay: 5
