FROM sheepkiller/kafka-manager:latest
MAINTAINER ThanhCL

# Copy Key Authen ###
COPY /tmp/cp-ansible/cert/kafka.server.keystore.jks /home/kafka.server.keystore.jks
COPY /tmp/cp-ansible/cert/kafka.server.truststore.jks /home/kafka.server.truststore.jks

# 