---
- name: Edit Kafka Rest
  hosts: kafka_rest
  tags: kafka_rest
  gather_facts: false
  become: yes
  
  tasks:
    - name: copy keystore & trustore to hosts
      copy: src=/tmp/cp-ansible/cert/{{ item }} dest=/var/ssl/private/
      with_items:
        - kafka.server.keystore.jks
        - kafka.server.truststore.jks

    - name: edit kafka rest ssl endpoint
      lineinfile:
        path: /etc/kafka-rest/kafka-rest.properties
        line: "{{ item.line }}"
      with_items:
        - { line: 'ssl.endpoint.identification.algorithm=' }
        - { line: 'client.ssl.endpoint.identification.algorithm=' }
        - { line: 'schema.registry.ssl.endpoint.identification.algorithm=' }
        - { line: 'access.control.allow.methods=GET,POST,PUT,DELETE,OPTIONS' }
        - { line: 'access.control.allow.origin=*' }
        - { line: 'consumer.request.timeout.ms=30000' }
      ignore_errors: yes

    - name: edit kafka rest trustore&keystore
      lineinfile:
        dest: /etc/kafka-rest/kafka-rest.properties
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^client.ssl.truststore.location', line: 'client.ssl.truststore.location=/var/ssl/private/kafka.server.truststore.jks' }
        - { regexp: '^client.ssl.keystore.location', line: 'client.ssl.keystore.location=/var/ssl/private/kafka.server.keystore.jks' }
        - { regexp: '^schema.registry.ssl.truststore.location', line: 'schema.registry.ssl.truststore.location=/var/ssl/private/kafka.server.truststore.jks' }
        - { regexp: '^schema.registry.ssl.keystore.location', line: 'schema.registry.ssl.keystore.location=/var/ssl/private/kafka.server.keystore.jks' }
        - { regexp: '^ssl.truststore.location', line: 'ssl.truststore.location=/var/ssl/private/kafka.server.keystore.jks' }
        - { regexp: '^ssl.keystore.location', line: 'ssl.keystore.location=/var/ssl/private/kafka.server.keystore.jks' }
        - { regexp: '^listeners', line: 'listeners=http://0.0.0.0:8082' }
      ignore_errors: yes

    - name: restart kafka rest 
      command: systemctl restart confluent-kafka-rest
      ignore_errors: yes
