---
- name: load sysctl
  command: sysctl -p

- name: reload systemd
  command: systemctl daemon-reload

- name: Restart Kafka
  systemd:
    name: "{{kafka_broker_service_name}}"
    state: restarted

- name: Wait for URP
  include_tasks: tasks/wait_for_urp.yml
